### ISSUE TITLE
npm run start throw en error 

### ISSUE THREAD

**Issue by wuyingfeng1992** [TimurRK/nestjs-example#3]
/Users/mac/Desktop/project/node/nestjs-example-master/node_modules/ts-node/src/index.ts:293
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/main.ts:16:32 - error TS2304: Cannot find name 'IAppSettings'.

16 const appSettings = config.get<IAppSettings>('APP_SETTINGS');

**Comment by TimurRK** [comment]
IAppSettings is a global interface.

Perhaps this is due to the fact that you have MacOS.

On my Linux, it starts normally.
